"""

makefile-generated migration

Rev. № e466678b7958
Revises № 
Creation date: 2025-08-19 21:20:27.555879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e466678b7958'
down_revision: str | None = None
branch_labels: str | list[str] | None = None
depends_on: str | list[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
